# -*- coding: utf-8 -*-
"""
/***************************************************************************
 DesireLines
                                 A QGIS plugin
 This plugin draws desirelines
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-03-16
        copyright            : (C) 2022 by zh33rmao
        email                : zh2ermao@dingtalk.com
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load DesireLines class from file DesireLines.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .desire_lines import DesireLines
    return DesireLines(iface)
